// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gahktmdqkwxvgqgrzjxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaGt0bWRxa3d4dmdxZ3J6anhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Njg0MjEsImV4cCI6MjA2NDQ0NDQyMX0.7wHJMof_2L1zWHLW5vdyDSqATlvadbctoYK8BVtyZow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);